### ISSUE TITLE
Provide new Canonical reference for a personal Article / Google Search Engine

### ISSUE THREAD

**Issue by Bas-Man** [selfhostedshow/wiki#112]
We often write our own blog posts. But we also want to share our content and attract more traffic to our sites. As well as avoiding issues with Google Search down grading our posts because of duplication.

I would like to propose that we add the ability for the wiki to provide an alternate canonical link reference.

This would be done though the use of two meta items in the markdown file.

```markdown
---
template: canonical.html
canonical: https://some-reference-to-original-post/
---

Original article content goes here.
```
This produces the resulting header code
```html
    --snip--
    <link href=https://some-reference-to-original-post/ rel=canonical>
    <link rel="shortcut icon" href=../img/favicon.ico>
    <title>Test - Self-Hosted Show Wiki</title>
    <link rel=stylesheet href=../assets/stylesheets/main.6910b76c.min.css>
    <link rel=stylesheet href=../assets/stylesheets/palette.196e0c26.min.css>
    <link href=https://fonts.gstatic.com rel=preconnect crossorigin>
    <link rel=stylesheet href="https://fonts.googleapis.com/css?family=Ubuntu:300,400,400i,700%7CUbuntu+Mono&display=fallback">
```
This produces the resulting page.
<img width="1302" alt="Screen Shot 2021-07-07 at 17 08 59" src="https://user-images.githubusercontent.com/6175103/124723913-76df9100-df46-11eb-8986-3c16404c16ad.png">

Of course the original canonical reference can be used by not having the *canonical:* reference. Or by not using the new template. 
Everything fails back gracefully.

The thinking behind this is it might encourage people to share their write ups on projects and help with Google Search.

I would ask for thoughts and feed back.

**Comment by py-crash** [comment]
Hi! This makes a lot of sense. The question is: How do we make sure that the article that you are contributing is actually yours?

**Comment by Bas-Man** [comment]
That is a good question.
I feel this should be part of the community guidelines. It would be great if we were all adults and respected others work. Sadly I guess this could be an issue.

**Comment by pagdot** [comment]
I don't think verification is possible. We could require that a contributor has to verify he is the author of the article by linking it to his blog. This wouldn't help though, if the blog article is already a copy of a different source.

E.g. I create my blog and fill it with articles by just copying them from any of you. I could verify that this is my blog, but without any of you complaining or investigating if this really is original content, I don't see a way to verify it.

I guess for most of us it wouldn't be an issue to link to our Github account on the blogs page, or the blog is versioned in a public git repository. This would allow easy verification for the reviewers and only little hurdles for the user contributing.

**Comment by Bas-Man** [comment]
Perhaps my title was misleading. 
My goal really is just allow writers to be able to cross post their content to the wiki while safely maintaining their own blog article as being canonical.

**Comment by Bas-Man** [comment]
Which looks better? Top, Bottom or having Both?
<img width="1268" alt="Screen Shot 2021-07-08 at 14 54 08" src="https://user-images.githubusercontent.com/6175103/124869627-6db0fb80-dffc-11eb-8e35-dac8436239ca.png">

**Comment by py-crash** [comment]
> Which looks better? Top, Bottom or having Both?
Bottom

**Comment by py-crash** [comment]
> My goal really is just to allow writers to be able to cross post their content to the wiki while safely maintaining their own blog article as being canonical.
> 
> Of course the content should be related to self hosting. And full articles and not simply links.

I think is a good idea to allow cross-posting. However, it should also be a good Idea to implement some guidelines with the template. E.g., the right licence, that you should be the author, a way to verify authorship (e.g. the same GitHub account, and/or the same E-mail as the account that creates the PR), etc.

**Comment by Bas-Man** [comment]
>n 
> 
> > My goal really is just to allow writers to be able to cross post their content to the wiki while safely maintaining their own blog article as being canonical.
> 

> 
> I think is a good idea to allow cross-posting. However, it should also be a good Idea to implement some guidelines with the template. E.g., the right licence, that you should be the author, a way to verify authorship (e.g. the same GitHub account, and/or the same E-mail as the account that creates the PR), etc.

That's above my pay grade. Probably something got Chris, Alex and the editor to discuss.

**Comment by Bas-Man** [comment]
This seems to have stalled. 
Any thoughts @IronicBadger ?

**Comment by Bas-Man** [comment]
Does anyone else have any thoughts on this. It's been 5months since my last request for feedback.

**Comment by BCNelson** [comment]
We could using something like https://keybase.io/ as it can verify the owners of both Github accounts as well as websites. the only down side i see is that keybase is not currently being actively maintained after they were acquired by Zoom.

**Comment by Bas-Man** [comment]
> We could using something like https://keybase.io/ as it can verify the owners of both Github accounts as well as websites.

How would that potentially work?

**Comment by WhiteNight121** [comment]
> > We could using something like https://keybase.io/ as it can verify the owners of both Github accounts as well as websites.
> 
> How would that potentially work?

i would think the person writing the article on a external site would need a keybase account and they would need to add both github and there own personal blog / website to keybase in order to prove that they "own" the content and they are not just pulling random articles from the internet and trying to say that they wrote them.

**Comment by py-crash** [comment]
Hi building in what @WhiteNight121 said. I would recommend some simple rules:

1. If the blog/original article is on GitHub and the PR comes from the same account, it should be accepted.
2. If the blog is of some other source sharing platform (e.g. GitLab), it should suffice with doing a signed PR on GitHub and a signed commit into the original repo using the same GPG-key
3. If the website is external, it should be verified with keybase and the PR should be signed with the same key available on keybase. Or at least that the Website and the GitHub account are both verified on keybase.

What do you think?

**Comment by Bas-Man** [comment]
This is above my pay grade and probably needs to go up the food chain.

**Comment by WhiteNight121** [comment]
@py-crash that works for me how do we make this happen?

**Comment by ironicbadger** [comment]
Why is the ownership piece so important? Requiring keybase seems like a hoop that might put folks off from contributing their stuff? 

This would mean we can't link to content we found elsewhere that would directly useful unless we own it too?

**Comment by Bas-Man** [comment]
Maybe I should clarify what my intention as well as how the template is intended to be used. 

- Using the new template is optional and does not change how normal pages can be written. You have to opt-in to the template.
- It's clear the wiki has not achieved much traction. The original thinking was to encourage people to add their original content which they may have written for their site. Giving them additional traffic and maintaining SEO. I thought this might be attentive to Alex and Chris as well as others who regularly write on self hosting topics.

**Comment by BCNelson** [comment]
I think that the verification requirement is only in place for people who are copying a whole article into the wiki. All other contributions are welcome with these extra steps.
