### ISSUE TITLE
30s links are broken

### ISSUE THREAD

**Issue by rastacalavera** [selfhostedshow/wiki#126]
links on the bottom of the page in the contribution-template.md 404, need to remove them or replace them.

**Comment by Bas-Man** [comment]
This is a template file for creating new contents. The links themselves should not be used in content that is being published.
That being said.  I will copy over the links found in CONTRIBUTING.md to resolve this 404 issue.

**Comment by Bas-Man** [comment]
This issue should have been resolved with pr #127
This should be closed.
