### ISSUE TITLE
glightbox issues

### ISSUE THREAD

**Issue by BrandonMayjeye** [selfhostedshow/wiki#137]
WARN[0000] /home/XXXX/Documents/wikibase/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
[+] Running 2/2
 ✔ Network wikibase_default   Created                                                               0.0s 
 ✔ Container wikibase-wiki-1  Created                                                               0.1s 
Attaching to wiki-1
wiki-1  | INFO    -  Building documentation... 
wiki-1  | ERROR   -  Config value: 'plugins'. Error: The "glightbox" plugin is not installed 
wiki-1  | 
wiki-1  | Aborted with 1 Configuration Errors!
wiki-1 exited with code 1

Fixed locally by removing 
```
plugins:
  - search
  - minify:
      minify_html: true
  - glightbox
  ```
  
  glitbox line from plugins in mkdocs.yml

**Comment by RealOrangeOne** [comment]
`glightbox` is an installed dependency. Have you tried rebuilding the container? Does it attempt to install it?

**Comment by BrandonMayjeye** [comment]
Sorry about the delay, 
yes rebuilding the container does in fact fix this issue
```❯ docker compose up --build```

and i now see what glightbox does, the theming is nice.
