### ISSUE TITLE
Article on docker

### ISSUE THREAD

**Issue by BCNelson** [selfhostedshow/wiki#15]
- installation
- docker-compose
- containers
- linuxerver.io

**Comment by anthr76** [comment]
Currently plan on working on docker-compose and home assistant this weekend. Gitting my docker-compose then taking my changes over.

**Comment by anthr76** [comment]
https://github.com/anthr76/docker-compose-hill/tree/testing This is just about finished though a few days behind. Also plan on writing docs for split tunneling over wireguard for docker container wireguard access.

**Comment by allout58** [comment]
This would be a good spot for https://composerize.com/ `eldudemeister` mentioned in Discord. https://discordapp.com/channels/693469700109369394/693473738552901644/699005478486671391

**Comment by patski123** [comment]
I wrote [this article](http://codeopolis.com/posts/25-basic-docker-commands-for-beginners/) on my blog a few days ago.  Someone on [this reddit post](https://www.reddit.com/r/selfhosted/comments/g3p37k/25_basic_docker_commands_for_beginners/) [converted it into Markdown](https://www.reddit.com/r/selfhosted/comments/g3p37k/25_basic_docker_commands_for_beginners/fntnfr9?utm_source=share&utm_medium=web2x) if you want to incorporate it into your wiki.

**Comment by BCNelson** [comment]
@patski123 We would love it if you added this or if you would like me to I just need to verify that your the author and giver permission to add this to the wiki. The best way that i know how to do that is [Keybase](https://keybase.io/) if you add proof of your github and the website the I will add the article to the wiki.

**Comment by WhiteNight121** [comment]
@BCNelson / @patski123  was this not already added in [45](https://github.com/selfhostedshow/wiki/pull/45)?

**Comment by BCNelson** [comment]
It is a link I assume that we would add the full texts

**Comment by WhiteNight121** [comment]
Hey @patski123 were you able to get keybase up and running?

**Comment by WhiteNight121** [comment]
i think this should be closed for now @BCNelson can reopen later as needed

**Comment by BCNelson** [comment]
Agreed
