### ISSUE TITLE
Beginners contributing guide

### ISSUE THREAD

**Issue by RealOrangeOne** [selfhostedshow/wiki#35]
The [contributing guide](https://github.com/selfhostedshow/wiki/blob/dev/CONTRIBUTING.md#how-to-contribute) already contains a great high-level guide on how to get started with contributing. But it'd be great for there to be something more beginner friendly. 

https://guides.github.com/ is a *great* resource for things like this!

As mentioned in https://selfhosted.show/15.

**Comment by WhiteNight121** [comment]
im going to start and work on this try and get a draft together...

**Comment by WhiteNight121** [comment]
ok its ready for review.... i hope added #57

**Comment by WhiteNight121** [comment]
@IronicBadger I think this one can be closed
