### ISSUE TITLE
Reference awesome-selfhosted

### ISSUE THREAD

**Issue by pagdot** [selfhostedshow/wiki#37]
In my opinion [Awesome-selfhosted](https://github.com/Kickball/awesome-selfhosted) should be referenced somewhere. There is already the link in the page about wikis, but there should be a reference on a more prominent page.

I would suggest one (or multiple) of the following locations:

- [The main page](https://selfhostedshow.github.io/wiki/) (but I think it wouldn't fit there)
- [Basic/Basics](https://selfhostedshow.github.io/wiki/basics/getting-started/)
- Self hosted apps main page (Doesn't exist yet; I don't know if this is supported by MkDocs or other tools)

I'm happy create a pull request, but would like to discuss a proper place first :)

**Comment by BCNelson** [comment]
I agree that is could be useful to reference somewhere however we just need to be careful that the [contribution guidelines](https://github.com/selfhostedshow/wiki/blob/dev/CONTRIBUTING.md) are met. see the first Point in What we are not trying to do

**Comment by pagdot** [comment]
Yeah, that's why I wanted to ask for the appropriate space :)

**Comment by WhiteNight121** [comment]
i like the basic location might be the best option for now

**Comment by pagdot** [comment]
Fixed in #96
