### ISSUE TITLE
Self host this repo?

### ISSUE THREAD

**Issue by Jab2870** [selfhostedshow/wiki#40]
I was wondering if you have considered self hosting this git repo, rather than relying on Microsoft's GitHub.

I understand that GitHub is great for discoverability, so perhaps mirroring a repo here would be a good idea, but there are a lot of really great self hosted git solutions out there.

I am in the process of moving [my repos](https://git.jonathanh.co.uk/explore/repos) over to [Gitea](https://gitea.io/en-us/).

There are obviously others

**Comment by RealOrangeOne** [comment]
This is something we considered, but something we intentionally *aren't* doing, mostly.

The nice thing about having the code live on GitHub is that it's incredibly easy for contribution and integration. Similar reasons why we have a [discord server](https://blog.ktz.me/self-hosted-launches-a-discord-server/).

We *do* intend to move the hosting and likely the CI off GitHub onto self-hosted infrastructure. We have a [Docker Container](https://github.com/selfhostedshow/wiki/packages/180256) setup ready for deployment, just need to get some servers setup to run it on.

**Comment by Jab2870** [comment]
Understood.

It just seemed a shame to be using a hosted service when there are excellent services available for self hosting, especially when self hosting is what this wiki will be.

Also, is discord the only "chat" service that is being used? I have recently come across the excellent podcast and would love to be involved in this community but discord is a step to far for me unfortunately.

**Comment by RealOrangeOne** [comment]
The irony definitely isn't lost on me!

Slightly tangential, but it's on my list to setup a [matrix](https://matrix.org/) server.

**Comment by py-crash** [comment]
Hi! The reasons to not to self host the repo where explained, so I would close the issue
