### ISSUE TITLE
Self-host the wiki

### ISSUE THREAD

**Issue by RealOrangeOne** [selfhostedshow/wiki#54]
For we are not hypocrites, we should be self-hosting this wiki! The intention is to host the web service itself, and CI further down the line, **not** the Git repo itself.

- [x] Allow the wiki to be run with a production-grade docker container (https://github.com/selfhostedshow/wiki/pull/18)
- [ ] Ensure the docker container is easily accessible (GitHub's registry requires auth, even for public containers, so isn't ideal)
- [ ] Get some server space (on hold)
- [x] Configure deployment (https://github.com/selfhostedshow/infrastructure)
- [ ] Setup DNS

Related: #40

**Comment by pagdot** [comment]
> Ensure the docker container is easily accessible (GitHub's registry requires auth, even for public containers, so isn't ideal)

So we should use the official Docker registry. It would allow easy access. Would it be possible to push to the official docker registry instead or additional to the Github registry?

**Comment by RealOrangeOne** [comment]
Yeah that's my plan!

I've created https://hub.docker.com/orgs/selfhostedshow, although now need to work out a nice way of pushing the image automatically, without using my own auth tokens or using a bot user.

**Comment by pagdot** [comment]
Another option would be to rewrite everything into a single Dockerfile containing a build step to build the static pages and one with the nginx installation + the static pages. It shouldn't be to hard to make it, but I don't know if you want it that way... I would be able to create an all-in-one Dockerfile in a Pull-request if you are interested in it

**Comment by RealOrangeOne** [comment]
@pagdot how would that fix things? We've got the container building just fine, we just need somewhere to put it.

**Comment by pagdot** [comment]
Sorry, forgot to write most of it :facepalm: 

I've meant building the container on the docker hub. As far as I know the docker hub doesn't support dependencies, which would requeire building a single Dockerfile. That's why we'd need to merge everything into one Dockerfile. As there is already a build pipeline using Github I don't think it that you would want it that way.

**Comment by IronicBadger** [comment]
This is *finally* done. 🥇
