### ISSUE TITLE
contributing.md vs CONTRIBUTING.md

### ISSUE THREAD

**Issue by WhiteNight121** [selfhostedshow/wiki#56]
not sure if this is correct or not but it looks like docs/wiki/contributing.md is just a link to  CONTRIBUTING.md should CONTRIBUTING.md replace contributing.md? as i dont see any of the other files linked just trying to keep everything the same.

**Comment by RealOrangeOne** [comment]
No this is intentionally just a reference.

Having a `CONTRIBUTING.md` file in the root is easy for people to find, and has some nice integrations with GitHub.

Putting the `contributing.md` file on the wiki itself enables it to be visible from the site itself, which is nice for people looking at what the wiki is and how to get started from that angle.

The reference is simply to avoid duplicating content. It's magically populated at build time.
