### ISSUE TITLE
CONTRIBUTING.md potential link failure / docker restarted needed after update.

### ISSUE THREAD

**Issue by Bas-Man** [selfhostedshow/wiki#76]
I was taking a look at CONTRIBUTE.md because of #74 and #75 
I have not made any changes. But it looks to me that 

```
See the [Beginners Contributing Guide](https://selfhostedshow.github.io/wiki/basics/beginners-contributing-guide/) for step by step instructions on how to add content.
```
This hardcode reference might be an issue down the line.

Also, because this file is referenced using `{!../CONTRIBUTING.md!}` in `wiki/contributing.md` any changes to the file require a restart of the docker image. I would propose that `CONTRIBUTING.md` physically be moved and no longer referenced.

Thoughts?

**Comment by IronicBadger** [comment]
Fixed.
