### ISSUE TITLE
Two versions of beginners-contributing-guide.md and out of sync with each other.

### ISSUE THREAD

**Issue by Bas-Man** [selfhostedshow/wiki#85]
There are two versions of `beginners-contributing-guide.md` one located at `docs/basics` and another at `docs/wiki`

These are clearly meant to be the same file. I would propose that one be chosen to be the holder of `truth` and the other converted to a reference similar to how `CONTRIBITING.md` is used for `docs/wiki/contribiting.md`
It appears that `wiki/beginners....` is the most up to date and is inline with the move from `dev` to `master` for the default branch.

This would allow for the two references. But the need to only edit a single file.

**Comment by IronicBadger** [comment]
`docs/basics` should be deleted - we only need one version of this page! And it belongs under the wiki heading IMHO.

**Comment by WhiteNight121** [comment]
I agree I'll try and try and look this weekend, as I noticed that there were 2 as well
